version: "3.9" # specify docker-compose version
services:
  server:
    container_name: event_server
    build: 
      context: . # specify the directory of the Dockerfile
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/go/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.1
    container_name: mongodb
    restart: always
    build: ./mongodb
    hostname: localhost
    ports:
      - 27000:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./mongodb/database:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGODB_SERVER=localhost
      - MONGODB_PORT=27017
      - MONGO_INITDB_DATABASE=organization
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    command: mongod